#!/usr/bin/env python
"""Generate a Chinese weekly top-journal tracking brief from weekly outputs."""

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "outputs"
DEFAULT_INPUT = OUTPUT_DIR / "weekly" / "weekly_latest_articles.csv"
DEFAULT_OUTPUT = OUTPUT_DIR / "weekly_top_journal_brief.md"
THEME_ORDER = [
    "AI",
    "innovation",
    "platform",
    "digital transformation",
    "China sample",
    "team science",
    "research commercialization",
    "intellectual property",
    "technology transfer",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate Chinese weekly top-journal brief.")
    parser.add_argument("--input", default=str(DEFAULT_INPUT), help="Weekly CSV generated by weekly_update.py.")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Markdown brief output path.")
    parser.add_argument("--top-n", type=int, default=12, help="Maximum highlighted articles.")
    return parser.parse_args()


def load_weekly(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(path)
    return pd.read_csv(path, dtype=str).fillna("")


def split_tags(value: str) -> list[str]:
    return [item.strip() for item in str(value or "").split(";") if item.strip()]


def theme_counts(df: pd.DataFrame) -> dict[str, int]:
    counts = {theme: 0 for theme in THEME_ORDER}
    for value in df.get("theme_tags", pd.Series(dtype=str)):
        for tag in split_tags(value):
            counts[tag] = counts.get(tag, 0) + 1
    return counts


def article_score(row: pd.Series) -> int:
    score = 0
    if str(row.get("is_research_relevant", "")).lower() == "true":
        score += 5
    score += 2 * len(split_tags(row.get("theme_tags", "")))
    if "China sample" in split_tags(row.get("theme_tags", "")):
        score += 2
    if "AI" in split_tags(row.get("theme_tags", "")):
        score += 1
    if row.get("pdf_url"):
        score += 1
    return score


def clean_cell(value: object) -> str:
    return str(value or "").replace("|", "\\|").strip()


def format_article(row: pd.Series, index: int) -> list[str]:
    tags = "; ".join(split_tags(row.get("theme_tags", "")) + split_tags(row.get("relevance_tags", "")))
    pdf_note = "有 OA PDF" if row.get("pdf_url") else "未记录 OA PDF"
    return [
        f"### {index}. {row.get('title', '')}",
        "",
        f"- 期刊：{row.get('journal', '')}",
        f"- 日期：{row.get('publication_date', '')}",
        f"- 标签：{tags or '无'}",
        f"- DOI：{row.get('doi', '') or 'N/A'}",
        f"- 链接：{row.get('article_url', '') or 'N/A'}",
        f"- PDF：{pdf_note}",
        "",
    ]


def write_brief(df: pd.DataFrame, output_path: Path, top_n: int) -> None:
    if df.empty:
        date_range = "无数据"
    else:
        date_range = f"{df['publication_date'].min()} 至 {df['publication_date'].max()}"

    relevant_mask = df.get("is_research_relevant", pd.Series(dtype=str)).astype(str).str.lower().eq("true")
    relevant_df = df.loc[relevant_mask].copy()
    if not relevant_df.empty:
        relevant_df["brief_score"] = relevant_df.apply(article_score, axis=1)
        relevant_df = relevant_df.sort_values(
            ["brief_score", "publication_date", "journal"], ascending=[False, False, True]
        )

    counts = theme_counts(df)
    journal_counts = df["journal"].value_counts().head(10) if "journal" in df else pd.Series(dtype=int)

    lines = [
        "# 每周顶刊追踪简报",
        "",
        f"- 周期：{date_range}",
        f"- 生成时间：{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"- 本周新文章：{len(df)} 篇",
        f"- 与研究方向相关：{len(relevant_df)} 篇",
        f"- Zotero BibTeX：{OUTPUT_DIR / 'weekly' / 'weekly_latest_articles.bib'}",
        f"- Zotero RIS：{OUTPUT_DIR / 'weekly' / 'weekly_latest_articles.ris'}",
        "",
        "## 一句话概览",
        "",
    ]

    if df.empty:
        lines.append("本周未抓取到新的 UTD24/FT50 文章。")
    else:
        active_themes = [f"{theme} {count} 篇" for theme, count in counts.items() if count]
        theme_text = "；".join(active_themes) if active_themes else "主题关键词命中较少"
        lines.append(f"本周共追踪到 {len(df)} 篇顶刊新文，其中 {len(relevant_df)} 篇命中研究相关规则；主题分布为：{theme_text}。")

    lines.extend(
        [
            "",
            "## 主题雷达",
            "",
            "| 主题 | 篇数 |",
            "| --- | ---: |",
        ]
    )
    lines.extend(f"| {theme} | {counts.get(theme, 0)} |" for theme in THEME_ORDER)

    lines.extend(["", "## 期刊来源 Top 10", "", "| 期刊 | 篇数 |", "| --- | ---: |"])
    if journal_counts.empty:
        lines.append("| 无 | 0 |")
    else:
        lines.extend(f"| {clean_cell(journal)} | {count} |" for journal, count in journal_counts.items())

    lines.extend(["", "## 建议优先阅读", ""])
    if relevant_df.empty:
        lines.append("暂无命中研究相关规则的文章。")
    else:
        for idx, (_, row) in enumerate(relevant_df.head(top_n).iterrows(), start=1):
            lines.extend(format_article(row, idx))

    lines.extend(
        [
            "## 全量清单",
            "",
            "| 日期 | 期刊 | 标题 | 标签 |",
            "| --- | --- | --- | --- |",
        ]
    )
    if df.empty:
        lines.append("| 无 | 无 | 无 | 无 |")
    else:
        for _, row in df.sort_values(["publication_date", "journal"], ascending=[False, True]).iterrows():
            tags = "; ".join(split_tags(row.get("theme_tags", "")) + split_tags(row.get("relevance_tags", "")))
            lines.append(
                f"| {clean_cell(row.get('publication_date', ''))} | {clean_cell(row.get('journal', ''))} | "
                f"{clean_cell(row.get('title', ''))} | {clean_cell(tags)} |"
            )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    df = load_weekly(Path(args.input))
    write_brief(df, Path(args.output), args.top_n)
    print(f"Wrote {Path(args.output).resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
